name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
            libssl-dev xsltproc wget unzip python3 rsync file pkg-config cmake

      - name: Download OpenWRT SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Clone OpenWRT packages repository
        run: |
          git clone --depth=1 https://github.com/openwrt/packages.git openwrt-packages
          mkdir -p openwrt-sdk/package/{libs,multimedia}

          # Clone OpenWRT core for OpenSSL
          git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt-core
          cp -r openwrt-core/package/libs/openssl openwrt-sdk/package/libs/libopenssl

          # Copy FFmpeg from packages
          cp -r openwrt-packages/multimedia/ffmpeg openwrt-sdk/package/multimedia/

          # Clone SRT package
          git clone --depth=1 https://github.com/Haivision/srt.git openwrt-srt
          cp -r openwrt-srt openwrt-sdk/package/libs/srt

          # Clone librist package
          git clone --depth=1 https://code.videolan.org/rist/librist.git openwrt-librist
          cp -r openwrt-librist openwrt-sdk/package/libs/librist

          # Update feeds
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare package directory
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Clean previous builds
        run: |
          rm -rf openwrt-sdk/build_dir/target-* openwrt-sdk/staging_dir/target-*

      - name: Check system resources
        run: |
          free -h
          df -h

      - name: Build the package
        run: |
          cd openwrt-sdk
          mkdir -p logs/package/srt-to-rist-gateway
          # Enable required kernel modules
          echo 'CONFIG_PACKAGE_kmod-md-mod=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-crypto-hash=y' >> .config
          echo 'CONFIG_PACKAGE_kmod-lib-crc32c=y' >> .config
          
          make defconfig
          
          # Build kernel and required modules first
          make target/linux/compile V=s
          
          # Build dependencies
          make package/ffmpeg/compile V=s
          make package/srt/compile V=s
          make package/librist/compile V=s
          
          # Build our package with verbose output
          make package/srt-to-rist-gateway/compile V=sc 2>&1 | tee logs/package/srt-to-rist-gateway/compile.txt || {
            echo "Build failed. Showing last 100 lines of logs:"
            tail -n 100 logs/package/srt-to-rist-gateway/compile.txt
            exit 1
          }

      - name: Upload .ipk package
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk
