name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
            libssl-dev xsltproc wget unzip python3 rsync file pkg-config cmake

      - name: Download OpenWRT SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Clone OpenWRT packages repository
        run: |
          # Configure Git for large repos
          git config --global http.postBuffer 524288000
          git config --global core.compression 9
          
          # Clone with retries
          for i in {1..3}; do
            git clone --depth=1 https://github.com/openwrt/packages.git openwrt-packages && break
            echo "Retrying clone... (attempt $i)"
            sleep 5
          done
          
          mkdir -p openwrt-sdk/package/{libs,multimedia}

          # Clone OpenWRT core for OpenSSL
          for i in {1..3}; do
            git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt-core && break
            echo "Retrying clone... (attempt $i)"
            sleep 5
          done
          cp -r openwrt-core/package/libs/openssl openwrt-sdk/package/libs/libopenssl

          # Copy FFmpeg from packages
          cp -r openwrt-packages/multimedia/ffmpeg openwrt-sdk/package/multimedia/

          # Clone SRT package
          for i in {1..3}; do
            git clone --depth=1 https://github.com/Haivision/srt.git openwrt-srt && break
            echo "Retrying clone... (attempt $i)"
            sleep 5
          done
          cp -r openwrt-srt openwrt-sdk/package/libs/srt

          # Clone librist package
          for i in {1..3}; do
            git clone --depth=1 https://code.videolan.org/rist/librist.git openwrt-librist && break
            echo "Retrying clone... (attempt $i)"
            sleep 5
          done
          cp -r openwrt-librist openwrt-sdk/package/libs/librist

          # Update feeds with retries
          cd openwrt-sdk
          for i in {1..3}; do
            ./scripts/feeds update -a && ./scripts/feeds install -a && break
            echo "Retrying feeds update... (attempt $i)"
            sleep 5
          done

      - name: Prepare package directory
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Clean previous builds
        run: |
          rm -rf openwrt-sdk/build_dir/target-* openwrt-sdk/staging_dir/target-*

      - name: Check system resources
        run: |
          free -h
          df -h

      - name: Build the package
        run: |
          cd openwrt-sdk
          
          # Enable all required packages and kernel modules
          cat > .config <<EOF
          CONFIG_ALL_NONSHARED=y
          CONFIG_ALL_KMODS=y
          CONFIG_ALL=y
          CONFIG_PACKAGE_librist=y
          CONFIG_PACKAGE_srt=y
          CONFIG_PACKAGE_libavformat=y
          CONFIG_PACKAGE_libavcodec=y
          CONFIG_PACKAGE_libavutil=y
          CONFIG_PACKAGE_libopenssl=y
          CONFIG_PACKAGE_srt-to-rist-gateway=y
          CONFIG_KERNEL_MD=y
          CONFIG_KERNEL_MD_RAID0=y
          CONFIG_KERNEL_MD_RAID1=y
          CONFIG_KERNEL_MD_RAID10=y
          CONFIG_KERNEL_MD_MULTIPATH=y
          CONFIG_PACKAGE_kmod-md-mod=y
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          EOF
          
          # Generate kernel config and build kernel first
          make defconfig
          make target/linux/compile V=s || {
            echo "Kernel compilation failed"
            exit 1
          }
          
          # Build all packages first to resolve dependencies
          make package/compile -j$(nproc) V=s || {
            echo "Package compilation failed"
            exit 1
          }
          
          # Finally build our package
          make package/srt-to-rist-gateway/compile -j$(nproc) V=s || {
            echo "Package build failed"
            exit 1
          }

      - name: Upload .ipk package
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk
