name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    env:
      TERM: xterm
      FORCE_UNSAFE_CONFIGURE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Cache OpenWRT SDK
        uses: actions/cache@v3
        with:
          path: |
            openwrt-sdk
            openwrt-packages
            openwrt-core
            openwrt-srt
            openwrt-librist
          key: ${{ runner.os }}-openwrt-sdk-23.05.3-${{ hashFiles('**/*.mk', '**/*.cmake', 'Makefile', 'feeds.conf') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-sdk-23.05.3-

      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses5-dev \
            libncursesw5-dev \
            zlib1g-dev \
            gawk \
            git \
            gettext \
            libssl-dev \
            xsltproc \
            wget \
            unzip \
            python3 \
            python3-pip \
            python3-setuptools \
            rsync \
            file \
            pkg-config \
            cmake \
            libtool \
            automake \
            autoconf \
            bison \
            flex \
            device-tree-compiler \
            ccache
          
          # Install Python dependencies via pip
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel

      - name: Download OpenWRT SDK
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Clone OpenWRT packages repository
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p openwrt-sdk/package/{libs,multimedia}
          
          # Clone main packages repo with specific branch
          git clone --depth=1 --branch openwrt-23.05 https://github.com/openwrt/packages.git openwrt-packages || exit 1
          
          # Clone OpenWRT core for OpenSSL
          git clone --depth=1 --branch openwrt-23.05 https://github.com/openwrt/openwrt.git openwrt-core || exit 1
          cp -r openwrt-core/package/libs/openssl openwrt-sdk/package/libs/libopenssl
          
          # Copy FFmpeg from packages
          cp -r openwrt-packages/multimedia/ffmpeg openwrt-sdk/package/multimedia/
          
          # Clone SRT package
          git clone --depth=1 https://github.com/Haivision/srt.git openwrt-srt || exit 1
          cp -r openwrt-srt openwrt-sdk/package/libs/srt
          
          # Clone librist package
          git clone --depth=1 https://code.videolan.org/rist/librist.git openwrt-librist || exit 1
          cp -r openwrt-librist openwrt-sdk/package/libs/librist

      - name: Update and install feeds
        run: |
          cd openwrt-sdk
          # Clean existing feeds
          rm -rf feeds tmp
          # Update feeds.conf with stable branches
          cat > feeds.conf <<EOF
          src-git packages https://github.com/openwrt/packages.git;openwrt-23.05
          src-git luci https://github.com/openwrt/luci.git;openwrt-23.05
          src-git routing https://github.com/openwrt/routing.git;openwrt-23.05
          src-git telephony https://github.com/openwrt/telephony.git;openwrt-23.05
          EOF
          
          # Update and install feeds
          ./scripts/feeds update -a || exit 1
          ./scripts/feeds clean
          ./scripts/feeds install -a -f || exit 1
          
          # Install specific packages
          ./scripts/feeds install ffmpeg
          ./scripts/feeds install libavcodec
          ./scripts/feeds install libavutil
          ./scripts/feeds install libavformat

      - name: Prepare package directory
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Clean previous builds
        run: |
          cd openwrt-sdk
          make clean
          rm -rf build_dir/target-* staging_dir/target-*
          rm -rf tmp

      - name: Configure build
        run: |
          cd openwrt-sdk
          
          # Create minimal config with required packages
          cat > .config <<EOF
          CONFIG_TARGET_mediatek_filogic=y
          CONFIG_TARGET_mediatek_filogic_DEVICE_glinet_gl-mt3000=y
          
          CONFIG_PACKAGE_librist=m
          CONFIG_PACKAGE_srt=m
          CONFIG_PACKAGE_ffmpeg=m
          CONFIG_PACKAGE_libopenssl=m
          CONFIG_PACKAGE_libpthread=m
          CONFIG_PACKAGE_srt-to-rist-gateway=m
          
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          
          CONFIG_FFMPEG_CUSTOM_ENCODERS=y
          CONFIG_FFMPEG_CUSTOM_DECODERS=y
          CONFIG_FFMPEG_CUSTOM_MUXERS=y
          CONFIG_FFMPEG_CUSTOM_DEMUXERS=y
          CONFIG_FFMPEG_CUSTOM_PARSERS=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOLS=y
          
          CONFIG_OPENSSL_ENGINE=y
          CONFIG_OPENSSL_OPTIMIZE_SPEED=y
          CONFIG_OPENSSL_WITH_ASM=y
          CONFIG_OPENSSL_WITH_DEPRECATED=y
          CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
          
          CONFIG_CCACHE=y
          EOF
          
          make defconfig
          make -j1 V=s config-dump

      - name: Build package
        run: |
          cd openwrt-sdk
          make package/srt-to-rist-gateway/compile V=s || {
            echo "Build failed. Checking logs..."
            find logs -type f -exec sh -c 'echo "=== {} ==="; cat {}' \;
            exit 1
          }

      - name: Upload .ipk package
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: openwrt-sdk/logs
