name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Cache OpenWRT SDK
        uses: actions/cache@v3
        with:
          path: |
            openwrt-sdk
            openwrt-packages
            openwrt-core
            openwrt-srt
            openwrt-librist
          key: ${{ runner.os }}-openwrt-sdk-23.05.3-${{ hashFiles('**/*.mk', '**/*.cmake', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-sdk-23.05.3-

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/workflows/build.yml') }}

      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
            libssl-dev xsltproc wget unzip python3 rsync file pkg-config cmake \
            libtool automake autoconf bison flex texinfo help2man ccache

      - name: Download OpenWRT SDK
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Clone OpenWRT packages repository
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p openwrt-sdk/package/{libs,multimedia}
          
          # Clone main packages repo
          git clone --depth=1 https://github.com/openwrt/packages.git openwrt-packages
          
          # Clone OpenWRT core for OpenSSL
          git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt-core
          cp -r openwrt-core/package/libs/openssl openwrt-sdk/package/libs/libopenssl
          
          # Copy FFmpeg from packages
          cp -r openwrt-packages/multimedia/ffmpeg openwrt-sdk/package/multimedia/
          
          # Clone SRT package
          git clone --depth=1 https://github.com/Haivision/srt.git openwrt-srt
          cp -r openwrt-srt openwrt-sdk/package/libs/srt
          
          # Clone librist package
          git clone --depth=1 https://code.videolan.org/rist/librist.git openwrt-librist
          cp -r openwrt-librist openwrt-sdk/package/libs/librist

      - name: Update and install feeds
        run: |
          cd openwrt-sdk
          # Clean existing feeds
          rm -rf feeds tmp
          # Update feeds.conf with stable branches
          echo "src-git packages https://github.com/openwrt/packages.git;openwrt-23.05" > feeds.conf
          echo "src-git luci https://github.com/openwrt/luci.git;openwrt-23.05" >> feeds.conf
          # Update and install feeds
          ./scripts/feeds update -a
          ./scripts/feeds clean
          ./scripts/feeds install -a -f -p packages
          ./scripts/feeds install -a -f -p luci

      - name: Prepare package directory
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Clean previous builds
        run: |
          cd openwrt-sdk
          make clean
          rm -rf build_dir/target-* staging_dir/target-*
          rm -rf tmp

      - name: Configure build
        run: |
          cd openwrt-sdk
          
          # Create minimal config with required kernel modules
          cat > .config <<EOF
          CONFIG_TARGET_mediatek_filogic=y
          CONFIG_TARGET_mediatek_filogic_DEVICE_glinet_gl-mt3000=y
          
          # Required kernel modules
          CONFIG_KERNEL_MIPS_FPU_EMULATOR=y
          CONFIG_KERNEL_MIPS_KERNEL_FPU=y
          CONFIG_KERNEL_KALLSYMS=y
          CONFIG_KERNEL_DEBUG_INFO=y
          CONFIG_KERNEL_DEBUG_INFO_REDUCED=n
          CONFIG_KERNEL_DEBUG_INFO_BTF=n
          CONFIG_KERNEL_AIO=y
          CONFIG_KERNEL_IO_URING=y
          CONFIG_KERNEL_FHANDLE=y
          CONFIG_KERNEL_FANOTIFY=y
          CONFIG_KERNEL_MAGIC_SYSRQ=y
          CONFIG_KERNEL_COREDUMP=y
          CONFIG_KERNEL_ELF_CORE=y
          CONFIG_KERNEL_PRINTK_TIME=y
          CONFIG_KERNEL_KEXEC=y
          CONFIG_KERNEL_PROC_VMCORE=y
          CONFIG_KERNEL_PROC_KCORE=y
          CONFIG_KERNEL_CRASH_DUMP=y
          CONFIG_KERNEL_KEYS=y
          CONFIG_KERNEL_CGROUPS=y
          CONFIG_KERNEL_FAIR_GROUP_SCHED=y
          CONFIG_KERNEL_PROC_PID_CPUSET=y
          
          # Required packages
          CONFIG_PACKAGE_librist=m
          CONFIG_PACKAGE_srt=m
          CONFIG_PACKAGE_libavformat=m
          CONFIG_PACKAGE_libavcodec=m
          CONFIG_PACKAGE_libavutil=m
          CONFIG_PACKAGE_libopenssl=m
          CONFIG_PACKAGE_srt-to-rist-gateway=m
          
          # Additional dependencies
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-lib-raid6=y
          CONFIG_PACKAGE_kmod-lib-xor=y
          CONFIG_PACKAGE_kmod-md-mod=y
          CONFIG_PACKAGE_kmod-md-linear=y
          CONFIG_PACKAGE_kmod-md-raid0=y
          CONFIG_PACKAGE_kmod-md-raid1=y
          CONFIG_PACKAGE_kmod-md-raid10=y
          CONFIG_PACKAGE_kmod-md-raid456=y
          
          # OpenSSL configuration
          CONFIG_OPENSSL_ENGINE=y
          CONFIG_OPENSSL_OPTIMIZE_SPEED=y
          CONFIG_OPENSSL_WITH_ASM=y
          CONFIG_OPENSSL_WITH_DEPRECATED=y
          CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
          
          # Disable all problematic packages
          CONFIG_PACKAGE_libopenssl-conf=n
          CONFIG_PACKAGE_libopenssl-legacy=n
          CONFIG_PACKAGE_libopenssl-padlock=n
          CONFIG_PACKAGE_openssl-util=n
          CONFIG_PACKAGE_wpa-supplicant-mesh-openssl=n
          CONFIG_PACKAGE_wpa-supplicant-openssl=n
          CONFIG_PACKAGE_eapol-test-openssl=n
          CONFIG_PACKAGE_gnunet-utils=n
          CONFIG_PACKAGE_checksec=n
          CONFIG_PACKAGE_luci-ssl-nginx=n
          CONFIG_PACKAGE_hostapd-openssl=n
          CONFIG_PACKAGE_wpad-mesh-openssl=n
          CONFIG_PACKAGE_wpad-openssl=n
          CONFIG_PACKAGE_nginx-ssl=n
          CONFIG_PACKAGE_nginx-ssl-util=n
          CONFIG_PACKAGE_nginx-mod-luci-ssl=n
          CONFIG_PACKAGE_luci-app-nginx=n
          CONFIG_PACKAGE_luci-ssl=n
          CONFIG_PACKAGE_luci-mod-admin-full=n
          CONFIG_PACKAGE_luci-theme-bootstrap=n
          CONFIG_PACKAGE_luci-theme-material=n
          CONFIG_PACKAGE_luci-theme-openwrt=n
          CONFIG_PACKAGE_wpad-basic-openssl=n
          
          # Disable all SSL variants
          CONFIG_PACKAGE_libustream-openssl=n
          CONFIG_PACKAGE_libustream-wolfssl=n
          CONFIG_PACKAGE_libustream-mbedtls=n
          EOF
          
          # Generate full config
          make defconfig

      - name: Build tools and toolchain
        run: |
          cd openwrt-sdk
          # Build tools with verbose output and single thread
          make tools/install -j1 V=s || {
            echo "Tools build failed. Checking logs..."
            find logs -type f -exec sh -c 'echo "=== {} ==="; cat {}' \;
            exit 1
          }
          # Build toolchain with verbose output and single thread
          make toolchain/install -j1 V=s || {
            echo "Toolchain build failed. Checking logs..."
            find logs -type f -exec sh -c 'echo "=== {} ==="; cat {}' \;
            exit 1
          }

      - name: Build package
        run: |
          cd openwrt-sdk
          make package/srt-to-rist-gateway/compile V=s || {
            echo "Build failed with error code $?"
            echo "Checking build logs..."
            find logs -type f -exec sh -c 'echo "=== {} ==="; cat {}' \;
            exit 1
          }

      - name: Upload .ipk package
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: openwrt-sdk/logs
