name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 rsync cmake pkg-config

      - name: Download OpenWRT SDK (mediatek/filogic)
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Install OpenWRT feed packages
        run: |
          cd openwrt-sdk
          echo "src-git packages https://git.openwrt.org/feed/packages.git^38cb0129b8d370c4d2c6e0e0f0bcc6d4d2ef56f5" > feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/symlinks

      - name: Copy package files only
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json README.md openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Debug build folder contents
        run: |
          echo "CMakeLists.txt content:"
          cat openwrt-sdk/package/srt-to-rist-gateway/CMakeLists.txt
          echo "Makefile content:"
          cat openwrt-sdk/package/srt-to-rist-gateway/Makefile

      - name: 🧼 Clean stale build cache
        run: |
          rm -rf openwrt-sdk/build_dir/target-*
          rm -rf openwrt-sdk/staging_dir/target-*

      - name: Build package
        run: |
          cd openwrt-sdk
          make defconfig
          make package/srt-to-rist-gateway/compile V=sc

      - name: Upload compiled .ipk
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk
