name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
            libssl-dev xsltproc wget unzip python3 rsync file pkg-config cmake

      - name: Configure Git
        run: |
          git config --global http.postBuffer 524288000
          git config --global core.compression 9
          git config --global http.lowSpeedLimit 1000
          git config --global http.lowSpeedTime 60

      - name: Download OpenWRT SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Clone OpenWRT packages repository
        run: |
          mkdir -p openwrt-sdk/package/{libs,multimedia}
          
          function clone_with_retry() {
            local repo=$1
            local dir=$2
            local max_attempts=5
            local attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Cloning $repo (attempt $attempt/$max_attempts)"
              if git clone --depth=1 "$repo" "$dir"; then
                return 0
              fi
              attempt=$((attempt + 1))
              sleep $((attempt * 5))
            done
            return 1
          }
          
          # Clone main packages repo
          clone_with_retry https://github.com/openwrt/packages.git openwrt-packages || exit 1
          
          # Clone OpenWRT core for OpenSSL
          clone_with_retry https://github.com/openwrt/openwrt.git openwrt-core || exit 1
          cp -r openwrt-core/package/libs/openssl openwrt-sdk/package/libs/libopenssl
          
          # Copy FFmpeg from packages
          cp -r openwrt-packages/multimedia/ffmpeg openwrt-sdk/package/multimedia/
          
          # Clone SRT package
          clone_with_retry https://github.com/Haivision/srt.git openwrt-srt || exit 1
          cp -r openwrt-srt openwrt-sdk/package/libs/srt
          
          # Clone librist package
          clone_with_retry https://code.videolan.org/rist/librist.git openwrt-librist || exit 1
          cp -r openwrt-librist openwrt-sdk/package/libs/librist

      - name: Update and install feeds
        run: |
          cd openwrt-sdk
          
          function update_feeds_with_retry() {
            local max_attempts=5
            local attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Updating feeds (attempt $attempt/$max_attempts)"
              if ./scripts/feeds update -a && ./scripts/feeds install -a; then
                return 0
              fi
              attempt=$((attempt + 1))
              sleep $((attempt * 5))
            done
            return 1
          }
          
          update_feeds_with_retry || exit 1

      - name: Prepare package directory
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Clean previous builds
        run: |
          rm -rf openwrt-sdk/build_dir/target-* openwrt-sdk/staging_dir/target-*
          rm -rf openwrt-sdk/tmp

      - name: Check system resources
        run: |
          free -h
          df -h

      - name: Configure build
        run: |
          cd openwrt-sdk
          
          # Create initial minimal config
          cat > .config <<EOF
          CONFIG_TARGET_mediatek_filogic=y
          CONFIG_TARGET_mediatek_filogic_DEVICE_glinet_gl-mt3000=y
          CONFIG_PACKAGE_librist=y
          CONFIG_PACKAGE_srt=y
          CONFIG_PACKAGE_libavformat=y
          CONFIG_PACKAGE_libavcodec=y
          CONFIG_PACKAGE_libavutil=y
          CONFIG_PACKAGE_libopenssl=y
          CONFIG_PACKAGE_srt-to-rist-gateway=y
          CONFIG_KERNEL_MD=y
          CONFIG_KERNEL_MD_RAID0=y
          CONFIG_KERNEL_MD_RAID1=y
          CONFIG_KERNEL_MD_RAID10=y
          CONFIG_KERNEL_MD_MULTIPATH=y
          CONFIG_PACKAGE_kmod-md-mod=y
          CONFIG_PACKAGE_kmod-crypto-hash=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          EOF
          
          # Generate full config
          make defconfig
          
          # Verify config
          make kernel_menuconfig
          make menuconfig

      - name: Build kernel and packages
        run: |
          cd openwrt-sdk
          
          # Build kernel first
          make target/linux/compile V=s || {
            echo "Kernel compilation failed"
            cat build.log
            exit 1
          }
          
          # Build base packages
          make package/libs/compile V=s || {
            echo "Base libraries compilation failed"
            cat build.log
            exit 1
          }
          
          # Build our package and dependencies
          make package/srt-to-rist-gateway/compile V=s || {
            echo "Package build failed"
            cat build.log
            exit 1
          }

      - name: Upload .ipk package
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk
