name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
            libssl-dev xsltproc wget unzip python3 rsync file pkg-config cmake

      - name: Download OpenWRT SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Clone OpenWRT packages repository
        run: |
          git clone --depth=1 https://github.com/openwrt/packages.git openwrt-packages
          ls -la openwrt-packages/libs/
          mkdir -p openwrt-sdk/package/libs

          # Ensure OpenSSL package exists
          if [ ! -d "openwrt-packages/libs/openssl" ] && [ ! -d "openwrt-packages/libs/libopenssl" ]; then
              echo "Cloning OpenSSL package from OpenWRT core..."
              git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt-openssl
              mkdir -p openwrt-packages/libs/
              cp -r openwrt-openssl/package/libs/openssl openwrt-packages/libs/
          fi

          # Copy SRT package
          if [ ! -d "openwrt-packages/libs/srt" ]; then
            echo "Error: SRT package not found"
            exit 1
          fi
          cp -r openwrt-packages/libs/srt openwrt-sdk/package/libs/ || { echo "Failed to copy SRT package"; exit 1; }

          # Copy OpenSSL package
          if [ -d "openwrt-packages/libs/openssl" ]; then
            cp -r openwrt-packages/libs/openssl openwrt-sdk/package/libs/libopenssl || { echo "Failed to copy OpenSSL package"; exit 1; }
          elif [ -d "openwrt-packages/libs/libopenssl" ]; then
            cp -r openwrt-packages/libs/libopenssl openwrt-sdk/package/libs/libopenssl || { echo "Failed to copy OpenSSL package"; exit 1; }
          else
            echo "Error: OpenSSL package not found in either libs/openssl or libs/libopenssl"
            exit 1
          fi

          # Verify copied packages
          ls -la openwrt-sdk/package/libs/

      - name: Prepare package directory
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Clean previous builds
        run: |
          rm -rf openwrt-sdk/build_dir/target-* openwrt-sdk/staging_dir/target-*

      - name: Check system resources
        run: |
          free -h
          df -h

      - name: Build the package
        run: |
          cd openwrt-sdk
          
          make defconfig
          
          # Build with dependencies
          make package/srt-to-rist-gateway/compile V=s || {
            echo "Build failed. Showing last 100 lines of logs:"
            tail -n 100 logs/package/srt-to-rist-gateway/compile.txt
            exit 1
          }

      - name: Debug .ipk location
        run: |
          find openwrt-sdk/bin/packages -name "srt-to-rist-gateway_*.ipk"

      - name: Upload .ipk package
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk
