name: Build OpenWRT IPK for GL-MT3000

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    name: Build srt-to-rist-gateway
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext \
            libssl-dev xsltproc wget unzip python3 rsync file pkg-config cmake

      - name: Download OpenWRT SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.3-mediatek-filogic_*.tar.xz
          mv openwrt-sdk-*/ openwrt-sdk

      - name: Clone OpenWRT packages repository
        run: |
          git clone --depth=1 https://github.com/openwrt/packages.git openwrt-packages
          mkdir -p openwrt-sdk/package/libs
          cp -r openwrt-packages/libs/srt openwrt-sdk/package/libs/

      - name: Prepare package directory
        run: |
          mkdir -p openwrt-sdk/package/srt-to-rist-gateway
          rsync -av src/ openwrt-sdk/package/srt-to-rist-gateway/src/
          rsync -av CMakeLists.txt Makefile config.json openwrt-sdk/package/srt-to-rist-gateway/
          if [ -d "init.d" ]; then rsync -av init.d openwrt-sdk/package/srt-to-rist-gateway/; fi

      - name: Clean previous builds
        run: |
          rm -rf openwrt-sdk/build_dir/target-* openwrt-sdk/staging_dir/target-*

      - name: Build the package
        run: |
          cd openwrt-sdk
          # Enable libsrt in config
          echo "CONFIG_PACKAGE_libsrt=y" >> .config
          make defconfig
          
          # Set PKG_CONFIG_PATH to find .pc files
          export PKG_CONFIG_PATH="$(pwd)/staging_dir/target-aarch64_cortex-a53_musl/usr/lib/pkgconfig:$(pwd)/staging_dir/target-aarch64_cortex-a53_musl/usr/share/pkgconfig"
          
          # Build libsrt first
          make package/libs/srt/compile V=s
          
          # Build our package
          make package/srt-to-rist-gateway/compile V=sc

      - name: Upload .ipk package
        uses: actions/upload-artifact@v4
        with:
          name: srt-to-rist-gateway-ipk
          path: openwrt-sdk/bin/packages/*/*/srt-to-rist-gateway_*.ipk
